#Pytest configuration

[pytest]
testpaths = tests
addopts = --html=reports/report.html --self-contained-html -v
markers =
    smoke: smoke tests critiques
    regression: Suite de régression complète
    api: Tests API uniquement
    End-to-end__tests: Tests UI Selenium