#Pytest configuration

[pytest]
testpaths = tests
addopts = --html=reports/report.html --self-contained-html -v
markers =
    smoke: critical smoke tests
    regression: full regression suite
    api: API tests
    End-to-end__tests: Selenium UI tests
    login: BDD tests related to login
    register: BDD tests related to register
    search: BDD tests related to product search
    cart: BDD tests related to cart